name: Serverless Action
on: [push]
jobs:
  setup:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: [12.x, 14.x, 16.x]
        os: [ubuntu-latest, windows-latest, macOS-11]
    steps:
      - name: check out on repository code
        uses: actions/checkout@v2
